language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/cache

env:
  global:
    - DB="mysql"
    - DB_NAME="ezpublish_test"
    - DB_USER="root"
    - TIMEZONE="Europe/Berlin"

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - vendor/bin/phing -Ddb.type=${DB} -Ddb.user=${DB_USER} -Ddb.database=${DB_NAME} test

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email: false
