before_commands:
    - "composer install -n"
filter:
    paths: [src/*]
    excluded_paths: [tests/*, vendor/*]
tools:
    external_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
    php_mess_detector:
        config:
            design_rules: { number_of_class_children: true, depth_of_inheritance: true }
            unused_code_rules: { unused_local_variable: true, unused_private_method: true, unused_formal_parameter: true }
            controversial_rules: { camel_case_class_name: true, camel_case_property_name: true, camel_case_method_name: true, camel_case_parameter_name: true, camel_case_variable_name: true }
    php_cpd: true